name: Deploy Juice Shop in CI

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Start Juice Shop Container
      run: |
        docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
        echo "Waiting for Juice Shop to start..."
        for i in {1..30}; do
          curl -s http://localhost:3000 > /dev/null && break
          echo "Waiting..."
          sleep 2
        done

    - name: Verify Juice Shop is Running
      run: |
        curl -s http://localhost:3000 | grep "OWASP Juice Shop" || exit 1
        echo "Juice Shop is up and running!"
