name: DevSecOps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast-semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep scan --config auto --sarif -o semgrep.sarif .
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  sast-codeql:
    name: Run CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - run: npm install
      - uses: github/codeql-action/analyze@v3

  deploy:
    name: Deploy Juice Shop (Docker)
    runs-on: ubuntu-latest
    needs: [sast-semgrep, sast-codeql]
    steps:
      - run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
          sleep 15

  dast-zap:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
