name: "OWASP ZAP DAST Scan"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap-dast:
    name: Run OWASP ZAP Baseline DAST Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start Juice Shop Container
      run: |
        docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
        echo "Waiting for Juice Shop to become available..."
        for i in {1..30}; do
          if curl -s http://localhost:3000 | grep -q "OWASP Juice Shop"; then
            echo "Juice Shop is ready!"
            break
          fi
          echo "Waiting for Juice Shop to be ready..."
          sleep 2
        done

    - name: Create ZAP config file
      run: |
        echo -e "90004\tIGNORE\tSpectre-related issue" >> zap-config.conf
        echo -e "90005\tIGNORE\tBrowser Sec-Fetch headers" >> zap-config.conf

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
        fail_action: false
        cmd_options: >
          -a
          -T 5
          -J report_json.json
          -w report_md.md
          -r report_html.html
          -c zap-config.conf
          -d

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-html
        path: report_html.html

    - name: Upload ZAP Markdown Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-md
        path: report_md.md
