name: ZAP Baseline Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Juice Shop (Background)
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

      - name: Wait for Juice Shop to start
        run: |
          sleep 10
          curl --retry 5 --retry-delay 5 --fail http://localhost:3000

      - name: Create ZAP Report Files
        run: |
          touch report_json.json report_md.md report_html.html
          chmod a+w report_json.json report_md.md report_html.html

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          cmd_options: >-
            -J report_json.json
            -w report_md.md
            -r report_html.html
            -a
            -T 5
            -c zap-config.conf
            -d

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: report_html.html

      - name: Upload ZAP Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: report_md.md

      - name: Upload ZAP JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: report_json.json
